# Generated by Django 5.1.3 on 2025-01-06 22:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Nota'),
        ),
    ]
