# Generated by Django 5.1.2 on 2024-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_servicio', models.CharField(max_length=20, verbose_name='Identificador')),
                ('nombre_anillo', models.CharField(max_length=20, verbose_name='Anillo')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Empresa')),
                ('nit', models.CharField(max_length=15, verbose_name='Nit')),
                ('nombre_contacto', models.CharField(max_length=30, verbose_name='Nombre contacto')),
                ('numero_contacto', models.CharField(max_length=15, verbose_name='Número contacto')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo contacto')),
                ('direccion_servicio', models.CharField(max_length=50, verbose_name='Dirección servicio')),
                ('ip', models.CharField(max_length=16, verbose_name='ip switch')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'ordering': ['-created'],
            },
        ),
    ]
