# Generated by Django 5.1.3 on 2025-03-19 20:31

from django.db import migrations

def assign_incidents_to_user(apps, schema_editor):
    # Obtén los modelos
    Incident = apps.get_model('incidents', 'Incident')
    User = apps.get_model('auth', 'User')
    
    # Asegúrate de que existe al menos un usuario
    if User.objects.exists():
        # Obtén el usuario (por ejemplo, el primer administrador)
        default_user = User.objects.filter(is_staff=True).first()
        if not default_user:
            default_user = User.objects.first()
        
        # Asigna todos los incidentes sin usuario a este usuario
        Incident.objects.filter(usuario__isnull=True).update(usuario=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_incident_usuario'),
    ]

    operations = [
        migrations.RunPython(assign_incidents_to_user),
    ]
